version: '3.8'

services:
  nginx:
    restart: unless-stopped
    networks:
      - dw-unlp_network
  redis:
    restart: unless-stopped
    networks:
      - dw-unlp_network
  db:
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - dw-unlp_network
  superset:
    restart: unless-stopped
    networks:
      - dw-unlp_network
  superset-worker:
    restart: unless-stopped
    networks:
      - dw-unlp_network
  superset-worker-beat:
    restart: unless-stopped
    networks:
      - dw-unlp_network

networks:
  dw-unlp_network:
    external: true